<?php

namespace common\models;

use common\traits\AttributesToInfoTrait;
use Yii;
use yii\web\UploadedFile;
use common\components\ActiveRecord;

/**
 * This is the model class for table "news".
 *
 * @property int $id
 * @property string|null $title
 * @property string|null $content
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property int|null $status
 * @property string|null $image
 */
class News extends ActiveRecord
{
    use AttributesToInfoTrait;

    const STATUS_DRAFT = 0;
    const STATUS_PUBLISH = 1;

    public $file;
    /**
     * {@inheritdoc}
     */

    public function attributesToInfo()
    {
        return [
            'tag_id'
        ];
    }
    public static function tableName()
    {
        return 'news';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['content'], 'string'],
            [['tag_id'], 'safe'],
            [['created_at', 'updated_at', 'status'], 'integer'],
            [['file'], 'file','extensions' => ['png', 'jpg', 'gif', 'PNG', 'JPG', 'GIF', 'JPEG', 'jpeg'],],
            [['title', 'image'], 'string', 'max' => 255],
        ];
    }
    /**
     * @param UploadedFile $file
     */
    private function saveFile(UploadedFile $file){
        $link = ($this->image) ? : null;
        $this->file = $file;
        if ($this->validate(['file'])) {
            $rand = uniqid(rand(), true);
            $dir = Yii::getAlias('@frontend/web/docs/news/');
            $dir2 = Yii::getAlias('docs/news/');
            $fileName = $rand . '.' . $this->file->extension;
            $this->file->saveAs($dir . $fileName);
            $this->file = $fileName; // без этого ошибка
            $link = '/'.$dir2 . $fileName;
        }

        $this->image = $link;
        $this->file = null;
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        $file = UploadedFile::getInstance($this, "file");
        if ($file && $file->tempName) {
            $this->saveFile($file);
        }
        if ($this->isNewRecord){
            $this->created_at = time();
        }
        $this->updated_at = time();
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }


    /**
     * @return array
     */
    public static function getStatusList(){
        return [
            self::STATUS_DRAFT => Yii::t('main', 'Черновик'),
            self::STATUS_PUBLISH => Yii::t('main', 'Опубликован'),
        ];
    }
    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Заголовок'),
            'content' => Yii::t('app', 'Содержание'),
            'created_at' => Yii::t('app', 'Дата публикации'),
            'updated_at' => Yii::t('app', 'Дата изменения'),
            'status' => Yii::t('app', 'Статус'),
            'image' => Yii::t('app', 'Картинка'),
        ];
    }
}
