<?php

namespace common\models;

use backend\models\BackendHelper;
use common\traits\AttributesToInfoTrait;
use Yii;
use yii\web\UploadedFile;
use common\components\ActiveRecord;

/**
 * This is the model class for table "settings".
 *
 * @property int $id
 * @property string|null $name
 * @property string|null $logo
 * @property string|null $phones
 * @property string|null $address
 * @property string|null $email
 * @property string|null $facebook
 * @property string|null $schedule
 * @property string|null $whatsapp
 * @property string|null $instagram
 * @property string|null $two_gis
 * @property string|null $map_x
 * @property string|null $map_y
 * @property string|null $url
 */
class Settings extends ActiveRecord
{
    public $image;
    public $phoneList;

    use AttributesToInfoTrait;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'settings';
    }

    public function attributesToInfo()
    {
        return [
            'header',
            'email',
            'facebook',
            'whatsapp',
            'instagram',
            'vk',
            'telegram',
            'youtube',
            'two_gis',
            'map_x',
            'map_y',
            'schedule',
            'main_banner',
            'about_us',
            'about_us_image',
            'benefits',
            'benefits_1',
            'benefits_2',
            'benefits_3',
            'for_who_name_1',
            'for_who_text_1',
            'for_who_name_2',
            'for_who_text_2',
            'for_who_name_3',
            'for_who_text_3',
            'how_it_1',
            'how_it_2',
            'how_it_3',
            'how_it_4',
            'how_it_5',
            'how_it_6',
            'footer_banner',
            'footer_slag',

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['phones', 'facebook','whatsapp','instagram','two_gis','vk','telegram', 'youtube', 'schedule'], 'string'],
            ['email','email'],
            [['header', 'about_us_image', 'main_banner', 'about_us', 'benefits', 'benefits_1', 'benefits_2', 'benefits_3', 'for_who_name_1', 'for_who_text_1', 'for_who_name_2', 'for_who_text_2', 'for_who_name_3', 'for_who_text_3', 'how_it_1', 'how_it_2', 'how_it_3', 'how_it_4', 'how_it_5', 'how_it_6', 'footer_banner', 'footer_slag'], 'safe'],
            [['phoneList', 'facebook','whatsapp','instagram','two_gis','map_x','map_y', 'schedule','email'], 'safe'],
            [['image'], 'file','extensions' => ['png', 'jpg', 'gif', 'PNG', 'JPG', 'GIF', 'JPEG', 'jpeg','svg', 'SVG'],],
            [['about_us_image'], 'file','extensions' => ['png', 'jpg', 'gif', 'PNG', 'JPG', 'GIF', 'JPEG', 'jpeg','svg', 'SVG'],],
            [['name', 'logo', 'address', 'url'], 'string', 'max' => 255],
            [['map_x','map_y'], 'double']
        ];
    }

    public function loadDefaultValues($skipIfSet = true)
    {
        $this->phoneList = isset($this->phones) ? json_decode($this->phones): [''];
        if (!$this->url){
            $this->url = BackendHelper::getUrl();
        }
        return parent::loadDefaultValues($skipIfSet); // TODO: Change the autogenerated stub
    }

    public function getPhoneNumbers(){
        return isset($this->phones) ? json_decode($this->phones): [];
    }



    /**
     * @param UploadedFile $file
     */
    private function saveFile(UploadedFile $file){
        $link = ($this->logo) ? : null;
        $this->image = $file;
        if ($this->validate(['file'])) {
            $rand = uniqid(rand(), true);
            $dir = Yii::getAlias('@frontend/web/docs/settings/');
            $dir2 = Yii::getAlias('docs/settings/');
            $fileName = $rand . '.' . $this->image->extension;
            $this->image->saveAs($dir . $fileName);
            $this->image = $fileName; // без этого ошибка
            $link = '/'.$dir2 . $fileName;
        }

        $this->logo = $link;
        $this->image = null;
    }

    /**
     * @param bool $runValidation
     * @param null $attributeNames
     * @return bool
     */
    public function save($runValidation = true, $attributeNames = null)
    {
        $file = UploadedFile::getInstance($this, "image");
        if ($file && $file->tempName) {
            $this->saveFile($file);
        }
        if ($this->phoneList) {
            $this->phones = json_encode($this->phoneList);
        }
        return parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
    }

    public function getMainPhone(){
        $phoneNumbers = $this->getPhoneNumbers();
        return  $phoneNumbers && sizeof($phoneNumbers) > 0 ? $phoneNumbers[0] : '';
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Название компании'),
            'header' => Yii::t('app', 'Заголовок сайта'),
            'image' => Yii::t('app', 'Логотип'),
            'logo' => Yii::t('app', 'Логотип'),
            'phones' => Yii::t('app', 'Телефоны'),
            'address' => Yii::t('app', 'Адрес'),
            'facebook' => Yii::t('app', 'Ссылка Facebook'),
            'instagram' => Yii::t('app', 'Ссылка Instagram'),
            'whatsapp' => Yii::t('app', 'Ссылка Whatsapp'),
            'two_gis' => Yii::t('app', 'Ссылка 2gis'),
            'map_x' => Yii::t('app', 'Широта в 2gis'),
            'map_y' => Yii::t('app', 'Долгота в 2gis'),
            'schedule' => Yii::t('app', 'График работы'),
            'email' => Yii::t('app', 'E-mail'),
            'url' => Yii::t('app', 'Url сайта'),
            //Первый баннер
            'main_banner' => Yii::t('app', 'Первый баннер'),
            //О нас
            'about_us' => Yii::t('app', 'О нас'),
            //Преимущества
            'benefits' => Yii::t('app', 'Преимущества'),
            'benefits_1' => Yii::t('app', 'Первое'),
            'benefits_2' => Yii::t('app', 'Второе'),
            'benefits_3' => Yii::t('app', 'Третье'),
            //Кому может пригодиться
            'for_who_name_1' => Yii::t('app', '1 Название'),
            'for_who_text_1' => Yii::t('app', '1 Текст'),
            'for_who_name_2' => Yii::t('app', '2 Название'),
            'for_who_text_2' => Yii::t('app', '2 Текст'),
            'for_who_name_3' => Yii::t('app', '3 Название'),
            'for_who_text_3' => Yii::t('app', '3 Текст'),
            //Как это работает
            'how_it_1' => Yii::t('app', 'Courses'),
            'how_it_2' => Yii::t('app', 'AuxPodcast'),
            'how_it_3' => Yii::t('app', 'AuxMart'),
            'how_it_4' => Yii::t('app', 'AuxCall'),
            'how_it_5' => Yii::t('app', 'AuxAdvice'),
            'how_it_6' => Yii::t('app', 'AuxNews'),
            //футер
            'footer_banner' => Yii::t('app', 'Поможем в выборе! Текст'),
            'footer_slag' => Yii::t('app', 'Слоган'),
        ];
    }
}
