<?php
namespace backend\components;
use yii\web\Controller;
use common\models\User;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\components\AccessRule;
class BaseAdminController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => [
                            User::ROLE_MODERATOR,
                            User::ROLE_ADMIN,
                            User::ROLE_SUPER_ADMIN,
                        ],
                    ],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (\Yii::$app->user->isGuest && $action->id != 'login'){
            return \Yii::$app->response->redirect('/site/login');
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}